### ISSUE TITLE
"Start Discussion" Button not updated after accepting the terms

### ISSUE THREAD

**Issue by broxinagil** [FriendsOfFlarum/terms#12]
Whe a user accepts the Terms, the "Start Discussion" Button stays deactivated. As well, when new Terms are published by an admin, mentioned button does not Change to deactivated.

Edit: As well the user does not see the discussions after accepting Terms before he refreshes the page

**Comment by clarkwinkelmann** [comment]
Good point.

I suppose the easiest at this point is to simply force a full page refresh after accepting the terms via the banner.
