### ISSUE TITLE
date format with the button "date now"

### ISSUE THREAD

**Issue by Angra974** [FriendsOfFlarum/terms#13]
Hi, just install it.
But, install on localhost and after send it via ftp to my server with the vendor/composer folder.
Install ok, up/down ok 
 but when i used the button for the date ( YYYY-MM-DD hh:mm:ss )
i've got this result : 2019-07-30T12:55:27.000Z

don't know if it's related to the extension or my configuration somewhere.
I use it for 2 docs ( privacy policies and convention ) and both with same error

**Comment by clarkwinkelmann** [comment]
Sorry we never replied on this, it must have slipped through.

Are you still experiencing the issue ?

What is the actual error message ? What you're seeing is the W3C date format and it's normal for the date to be inputted in that format when using the "now" button. The extension should accept that format when you save. The date field actually support any date format recognized by the Carbon PHP library we use.

**Comment by clarkwinkelmann** [comment]
I'm closing this issue, feel free to reply if you continue experiencing issues, we'll re-open. Thanks.
