### ISSUE TITLE
Option to withdraw acceptance of terms (optional consents).

### ISSUE THREAD

**Issue by rafaucau** [FriendsOfFlarum/terms#33]
## Feature Request
An option to add optional terms would be useful. E.g. Marketing consents, etc.
Currently this extension requires acceptance of all terms and does not allow you to withdraw from them.

- In the admin panel add a checkbox "This terms are optional".
- If the terms are optional then the extension should not require it
- User in profile settings can withdraw consent

**Comment by clarkwinkelmann** [comment]
This could indeed be added without too much complexity.

I think I remember discussing something similar in the past where I shared the concern that an opt-in-and-out checkbox would likely be liked with some automated feature and therefore would make more sense as part of a different extension.

How would the forum owner integrate with such an optional policy? It's likely too much work if they need to visit each user profile to check the value before, for example, sending a newsletter. There is already an export API but adding this feature might imply we need to expose a more advanced export API or webhooks, which then creates a lot more things to maintain.
